version: '3'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Iseestars
    volumes:
      - '/data/pg:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  myapp:
    build:
      context: .
      dockerfile: libs/.docker/postgres.Dockerfile
    depends_on:
      - postgres
    ports:
      - "8014:8014"